from . import secret

ENV = {
    "DATABASE_NAME":secret.DATABASE_NAME,
    "DATABASE_USER":secret.DATABASE_USER,
    "DATABASE_PASSWORD":secret.DATABASE_PASSWORD,
    "DATABASE_HOST":secret.DATABASE_HOST,
    "DATABASE_PORT":secret.DATABASE_PORT,
    "DEBUG_MODE":secret.DEBUG_MODE,
    "ALLOWED_HOSTS":secret.ALLOWED_HOSTS,
    "SECRET_KEY":secret.SECRET_KEY,
    # "FIREBASE_KEY_FILE":secret.FIREBASE_KEY_FILE
}